# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import groupsapp_pb2 as groupsapp__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in groupsapp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/groupsapp.AuthService/Register',
                request_serializer=groupsapp__pb2.RegisterRequest.SerializeToString,
                response_deserializer=groupsapp__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/groupsapp.AuthService/Login',
                request_serializer=groupsapp__pb2.LoginRequest.SerializeToString,
                response_deserializer=groupsapp__pb2.AuthResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=groupsapp__pb2.RegisterRequest.FromString,
                    response_serializer=groupsapp__pb2.AuthResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=groupsapp__pb2.LoginRequest.FromString,
                    response_serializer=groupsapp__pb2.AuthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'groupsapp.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('groupsapp.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groupsapp.AuthService/Register',
            groupsapp__pb2.RegisterRequest.SerializeToString,
            groupsapp__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groupsapp.AuthService/Login',
            groupsapp__pb2.LoginRequest.SerializeToString,
            groupsapp__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GroupServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGroup = channel.unary_unary(
                '/groupsapp.GroupService/CreateGroup',
                request_serializer=groupsapp__pb2.CreateGroupRequest.SerializeToString,
                response_deserializer=groupsapp__pb2.GroupResponse.FromString,
                _registered_method=True)
        self.JoinGroup = channel.unary_unary(
                '/groupsapp.GroupService/JoinGroup',
                request_serializer=groupsapp__pb2.JoinGroupRequest.SerializeToString,
                response_deserializer=groupsapp__pb2.GroupResponse.FromString,
                _registered_method=True)
        self.ListMyGroups = channel.unary_unary(
                '/groupsapp.GroupService/ListMyGroups',
                request_serializer=groupsapp__pb2.ListMyGroupsRequest.SerializeToString,
                response_deserializer=groupsapp__pb2.ListMyGroupsResponse.FromString,
                _registered_method=True)


class GroupServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMyGroups(self, request, context):
        """← NUEVO
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroup,
                    request_deserializer=groupsapp__pb2.CreateGroupRequest.FromString,
                    response_serializer=groupsapp__pb2.GroupResponse.SerializeToString,
            ),
            'JoinGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGroup,
                    request_deserializer=groupsapp__pb2.JoinGroupRequest.FromString,
                    response_serializer=groupsapp__pb2.GroupResponse.SerializeToString,
            ),
            'ListMyGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMyGroups,
                    request_deserializer=groupsapp__pb2.ListMyGroupsRequest.FromString,
                    response_serializer=groupsapp__pb2.ListMyGroupsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'groupsapp.GroupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('groupsapp.GroupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroupService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groupsapp.GroupService/CreateGroup',
            groupsapp__pb2.CreateGroupRequest.SerializeToString,
            groupsapp__pb2.GroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groupsapp.GroupService/JoinGroup',
            groupsapp__pb2.JoinGroupRequest.SerializeToString,
            groupsapp__pb2.GroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMyGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groupsapp.GroupService/ListMyGroups',
            groupsapp__pb2.ListMyGroupsRequest.SerializeToString,
            groupsapp__pb2.ListMyGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/groupsapp.MessageService/SendMessage',
                request_serializer=groupsapp__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=groupsapp__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_unary(
                '/groupsapp.MessageService/GetMessages',
                request_serializer=groupsapp__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=groupsapp__pb2.MessagesResponse.FromString,
                _registered_method=True)


class MessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=groupsapp__pb2.SendMessageRequest.FromString,
                    response_serializer=groupsapp__pb2.MessageResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=groupsapp__pb2.GetMessagesRequest.FromString,
                    response_serializer=groupsapp__pb2.MessagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'groupsapp.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('groupsapp.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groupsapp.MessageService/SendMessage',
            groupsapp__pb2.SendMessageRequest.SerializeToString,
            groupsapp__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groupsapp.MessageService/GetMessages',
            groupsapp__pb2.GetMessagesRequest.SerializeToString,
            groupsapp__pb2.MessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DiscoveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterP2P = channel.unary_unary(
                '/groupsapp.DiscoveryService/RegisterP2P',
                request_serializer=groupsapp__pb2.RegisterP2PRequest.SerializeToString,
                response_deserializer=groupsapp__pb2.RegisterP2PResponse.FromString,
                _registered_method=True)
        self.GetGroupOnlinePeers = channel.unary_unary(
                '/groupsapp.DiscoveryService/GetGroupOnlinePeers',
                request_serializer=groupsapp__pb2.GetGroupPeersRequest.SerializeToString,
                response_deserializer=groupsapp__pb2.GetGroupPeersResponse.FromString,
                _registered_method=True)


class DiscoveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterP2P(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupOnlinePeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterP2P': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterP2P,
                    request_deserializer=groupsapp__pb2.RegisterP2PRequest.FromString,
                    response_serializer=groupsapp__pb2.RegisterP2PResponse.SerializeToString,
            ),
            'GetGroupOnlinePeers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupOnlinePeers,
                    request_deserializer=groupsapp__pb2.GetGroupPeersRequest.FromString,
                    response_serializer=groupsapp__pb2.GetGroupPeersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'groupsapp.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('groupsapp.DiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterP2P(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groupsapp.DiscoveryService/RegisterP2P',
            groupsapp__pb2.RegisterP2PRequest.SerializeToString,
            groupsapp__pb2.RegisterP2PResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupOnlinePeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groupsapp.DiscoveryService/GetGroupOnlinePeers',
            groupsapp__pb2.GetGroupPeersRequest.SerializeToString,
            groupsapp__pb2.GetGroupPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PresenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdatePresence = channel.stream_stream(
                '/groupsapp.PresenceService/UpdatePresence',
                request_serializer=groupsapp__pb2.PresenceUpdate.SerializeToString,
                response_deserializer=groupsapp__pb2.PresenceUpdate.FromString,
                _registered_method=True)


class PresenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdatePresence(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PresenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdatePresence': grpc.stream_stream_rpc_method_handler(
                    servicer.UpdatePresence,
                    request_deserializer=groupsapp__pb2.PresenceUpdate.FromString,
                    response_serializer=groupsapp__pb2.PresenceUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'groupsapp.PresenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('groupsapp.PresenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PresenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdatePresence(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/groupsapp.PresenceService/UpdatePresence',
            groupsapp__pb2.PresenceUpdate.SerializeToString,
            groupsapp__pb2.PresenceUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
